#!/bin/sh

PNAME=FastRWeb
SWD=`pwd`
echo "Removing previous dist ..."
rm -rf /tmp/${PNAME}
echo "Copying package base ..."
cp -r ../${PNAME} /tmp

rm -f /tmp/${PNAME}/mkdist

cd /tmp/${PNAME}

echo "Removing CVS and backup stuff ..."
find . -name CVS -o -name .svn | xargs rm -rf
find . -name \*~ | xargs rm -f

echo "Updating version ..."
VER=`awk -v ORS= '/Version:/ { print $2 }' DESCRIPTION`
echo "$PNAME version ${VER}"

echo "Creating package ..."
cd ..
R CMD build ${PNAME}
cd ${SWD}
cp /tmp/${PNAME}_${VER}.tar.gz ..
rm -rf /tmp/${PNAME}
echo "Done."
ls -l ../${PNAME}_${VER}.tar.gz
